# -*- coding: utf-8 -*-
"""Aula6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rKA1-2ev3Uz2m4Ggz1N5xjOy7_R0Rq7D
"""

turmas = ["3A", "3B", "3C", "3D"]
grade_horaria = {
    "3A": {
        "professor": "Bernardo",
        "slot": ("segunda", "15:50-17:35"),
        "sala": "Lab 2",
    },
    "3B": {
        "professor": "Gordo",
        "slot": ("quarta", "13:50-17:35"),
        "sala": "Lab Barroca",
    },
    "3C": {
        "professor": "Renato",
        "slot": ("quinta", "13:50-15:30"),
        "sala": "Lab 2",
    },
    "3D": {
        "professor": "Rubens",
        "slot": ("terça", "15:50-17:35"),
        "sala": "Lab 1",
    },
}

professor_disciplinas = {
        "Bernardo": "BD2",
        "Gordo": "RAC",
        "Renato": "TPA",
        "Rubens": "Python",
}

salas = {"Lab 2", "Lab 1", "Lab Barroca"}


for turma in turmas:
    info = grade_horaria.get(turma)
    if info is None:
        print(f"Turma {turma} ainda sem alocação.")
    else:
        dia, hora = info["slot"]
        print(
            f"Turma {turma}: {info['professor']} - {info['slot']} - Sala {info['sala']}"
        )

print("\nSalas distintas:", salas)
print(f"O número de salas distintas é igual a", len(salas))
print("\nProfessores e suas matérias:", professor_disciplinas)