# -*- coding: utf-8 -*-
"""aula7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hPg01qSDjztxvAZfsOmKGvUiwI_Yhisk
"""

def Questao1():
  salario = float(input("Digite seu salário: "))
  if (salario<=280.0):
    porcentagem = 20
    valor_aum = salario * (porcentagem / 100)
    reajuste = salario+valor_aum
  elif (salario>280.0 and salario<700.0):
    porcentagem = 20
    valor_aum = salario * (porcentagem / 100)
    reajuste = salario+valor_aum
  elif (salario<1500.0 and salario>700.0):
    porcentagem = 20
    valor_aum = salario * (porcentagem / 100)
    reajuste = salario+valor_aum
  else:
    porcentagem = 20
    valor_aum = salario * (porcentagem / 100)
    reajuste = salario+valor_aum
  print("O salário antes do reajuste: {}, o percentual de aumento: {}%, o valor do aumento: {} e o salário após o reajuste: {}" .format(salario, porcentagem, valor_aum, reajuste))

def Questao2():
  salario = float(input("Digite o valor do sua hora: "))
  horas = float(input("Digite as horas trabalhadas: " ))

  salario_tot = salario*horas
  if(salario_tot<=900):
    print("Você está isento do IR")
  elif(salario_tot>=900 and salario_tot<=1500):
    salario_rea = salario_tot * 0.95
    print("Você tem 5% de desconto então seu salário reajustado é: {} " .format(salario_rea))
  elif(salario_tot>=1500 and salario_tot<=2500):
    salario_rea = salario_tot * 0.90
    print("Você tem 10% de desconto então seu salário reajustado é: {} " .format(salario_rea))
  else:
    salario_rea = salario_tot * 0.80
    print("Você tem 10% de desconto então seu salário reajustado é: {} " .format(salario_rea))
  print("Você tem {} horas trabalhadas e seu valor da hora é {}" .format(salario, horas))

def Questao3():
  lado1 = float(input("Digite o valor do 1º lado do triângulo:"))
  lado2 = float(input("Digite o valor do 2º lado do triângulo:"))
  lado3 = float(input("Digite o valor do 3º lado do triângulo:"))

  if (lado1+lado2<=lado3):
    print("Pode ser um triângulo")
    if(lado1==lado2 and lado2==lado3):
      print("É um triângulo equilátero")
    elif(lado1==lado2 or lado2==lado3):
      print("É um triângulo isósceles")
    elif(lado1!=lado2 and lado2!=lado3):
      print("É um triângulo escaleno")
  elif (lado1+lado3<=lado2):
    print("Pode ser um triângulo")
    if(lado1==lado2 and lado2==lado3):
      print("É um triângulo equilátero")
    elif(lado1==lado2 or lado2==lado3):
      print("É um triângulo isósceles")
    elif(lado1!=lado2 and lado2!=lado3):
      print("É um triângulo escaleno")
  elif (lado2+lado3<=lado3):
    print("Pode ser um triângulo")
    if(lado1==lado2 and lado2==lado3):
      print("É um triângulo equilátero")
    elif(lado1==lado2 or lado2==lado3):
      print("É um triângulo isósceles")
    elif(lado1!=lado2 and lado2!=lado3):
      print("É um triângulo escaleno")
  else:
    print("Não pode ser um triângulo")

questao = input("Opções: Questao1, Questao2, Questao3! Digite qual questão quer ter acesso:")
if questao=="Questao1":
  print(Questao1())

elif questao=="Questao2":
  print(Questao1())

elif questao=="Questao13":
  print(Questao1())