# -*- coding: utf-8 -*-
"""Aula4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yyro62NOZ6kUpEdT2GwtFbKhxsU0OlaV

Questao1 / Questao2 / Questao3
"""

#questao1
listaA = [1, 2, 3]
listaB = [2, 3, 4]
listaC = [5, 6, 7]

#questao2
print(listaA + listaB)
print(len(listaC))
listaB.append(5)
listaB.append(6)
print(listaB)
listaA.remove(3)
print(listaA)
listaB.insert(1, 10)
print(listaB)

#questao3
lista3 = [1, 2, 3, 4, 5]
meio = len(lista3) // 2
print(lista3[meio])