# -*- coding: utf-8 -*-
"""aula5_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LyuA7YwLIl7ev1fYus0q6PgaAhuGXq_D

Questao2
"""

import math

area = float(input("digite a quantidade de metros quadrados da area que sera pintada: "))
area_nova = area * 1.1 # 10% de folga
qnt_litros = area_nova/6 # quantos litros ele vai precisar no final

# resposta 1ª situação
galoes18 = math.ceil(qnt_litros/18)
preco1 = galoes18 * 80
print(preco1)
print(galoes18)
print(qnt_litros)

# resposta 2ª situação
galoes36 = math.ceil(qnt_litros/3.6)
preco2 = galoes36 * 25
print(preco2)
print(galoes36)

# resposta 3ª situação
if qnt_litros % 18 == 0 :
  print("A 1ª situação é ideal")
elif qnt_litros % 3.6 ==0 :
  print("A 2ª situação é ideal")
else:
  if qnt_litros > 18:
    INTEIRO18 = qnt_litros // 18
    resto18 = qnt_litros % 18
    resto36 = math.ceil(resto18/3.6)
    print("Quant latas 18: {}, quant latas 3,6: {}" .format(INTEIRO18, resto36))
  else:
    resto36 = math.ceil(qnt_litros/3.6)
    print("quannt latas 3,6: {}" .format(resto36))

