# -*- coding: utf-8 -*-
"""Aula5_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11CnPZlap-dNaI4Td2lTBZoQGPX-tslcO

Questao1
"""

salario = float(input("Digite o valor do sua hora: "))
horas = float(input("Digite as horas trabalhadas: " ))
salario_rea = salario*horas
print("O salário bruto é R${}" .format(salario_rea))
inss = salario_rea * 0.08
print("O valor dedicado ao INSS é R${}" .format(inss))
sindi = salario_rea * 0.05
print("O valor dedicado ao sindicato é R${}" .format(sindi))
imposto_renda = salario_rea * 0.11
salario_liqui = salario_rea - (sindi+inss+imposto_renda)
print("O salário líquido é R${}" .format(sakario_liqui))