# -*- coding: utf-8 -*-
"""aula5_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16nPCB2hzC4XxyAnmHR452HLBPedk_3bg
"""

tipo = input("Digite o tipo de combustível comprado: ")
num_litros = float(input("Digite o número de litros comprados: "))

if tipo == "A":
  if num_litros <= 20:
    desc_preco_litro = 1.9 * 0.97 # desconto de 3% já aplicado no preço de cada litro -> 97% de R$1,9
  else:
    desc_preco_litro = 1.9 * 0.95 # desconto de 5% já aplicado no preço de cada litro -> 95% de R$1,9

  valor_reaj = num_litros * desc_preco_litro # qnt litros multiplicada pelo novo valor do litro(com X porcentagem de desconto)
  print("O valor ajustado de acordo com as circunstâncias informadas é : R${}" .format(valor_reaj))

elif tipo == "G":
  if num_litros <= 20:
    desc_preco_litro = 2.5 * 0.96 # desconto de 4% já aplicado no preço de cada litro -> 96% de R$2,5
  else:
    desc_preco_litro = 2.5 * 0.94 # desconto de 5% já aplicado no preço de cada litro -> 94% de R$2,5

  valor_reaj = num_litros * desc_preco_litro # qnt litros multiplicada pelo novo valor do litro(com X porcentagem de desconto)
  print("O valor ajustado de acordo com as circunstâncias informadas é : R${}" .format(valor_reaj))